// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/prompt_messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PromptTemplate represents a template for generating prompts.
type PromptTemplate struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateString          string                 `protobuf:"bytes,2,opt,name=template_string,json=templateString,proto3" json:"template_string,omitempty"`
	DefaultContextModifiers map[string]string      `protobuf:"bytes,3,rep,name=default_context_modifiers,json=defaultContextModifiers,proto3" json:"default_context_modifiers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PromptTemplate) Reset() {
	*x = PromptTemplate{}
	mi := &file_proto_prompt_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptTemplate) ProtoMessage() {}

func (x *PromptTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prompt_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptTemplate.ProtoReflect.Descriptor instead.
func (*PromptTemplate) Descriptor() ([]byte, []int) {
	return file_proto_prompt_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PromptTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PromptTemplate) GetTemplateString() string {
	if x != nil {
		return x.TemplateString
	}
	return ""
}

func (x *PromptTemplate) GetDefaultContextModifiers() map[string]string {
	if x != nil {
		return x.DefaultContextModifiers
	}
	return nil
}

// PromptGenerationRequest represents a request to generate a prompt.
type PromptGenerationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TemplateId       string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	DynamicVariables map[string]string      `protobuf:"bytes,2,rep,name=dynamic_variables,json=dynamicVariables,proto3" json:"dynamic_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContextModifiers map[string]string      `protobuf:"bytes,3,rep,name=context_modifiers,json=contextModifiers,proto3" json:"context_modifiers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PromptGenerationRequest) Reset() {
	*x = PromptGenerationRequest{}
	mi := &file_proto_prompt_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptGenerationRequest) ProtoMessage() {}

func (x *PromptGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prompt_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptGenerationRequest.ProtoReflect.Descriptor instead.
func (*PromptGenerationRequest) Descriptor() ([]byte, []int) {
	return file_proto_prompt_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PromptGenerationRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *PromptGenerationRequest) GetDynamicVariables() map[string]string {
	if x != nil {
		return x.DynamicVariables
	}
	return nil
}

func (x *PromptGenerationRequest) GetContextModifiers() map[string]string {
	if x != nil {
		return x.ContextModifiers
	}
	return nil
}

// GeneratedPrompt represents a generated prompt.
type GeneratedPrompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromptString  string                 `protobuf:"bytes,1,opt,name=prompt_string,json=promptString,proto3" json:"prompt_string,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedPrompt) Reset() {
	*x = GeneratedPrompt{}
	mi := &file_proto_prompt_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedPrompt) ProtoMessage() {}

func (x *GeneratedPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prompt_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedPrompt.ProtoReflect.Descriptor instead.
func (*GeneratedPrompt) Descriptor() ([]byte, []int) {
	return file_proto_prompt_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GeneratedPrompt) GetPromptString() string {
	if x != nil {
		return x.PromptString
	}
	return ""
}

func (x *GeneratedPrompt) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_prompt_messages_proto protoreflect.FileDescriptor

const file_proto_prompt_messages_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/prompt_messages.proto\x12\n" +
	"prometheus\"\x8a\x02\n" +
	"\x0ePromptTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0ftemplate_string\x18\x02 \x01(\tR\x0etemplateString\x12s\n" +
	"\x19default_context_modifiers\x18\x03 \x03(\v27.prometheus.PromptTemplate.DefaultContextModifiersEntryR\x17defaultContextModifiers\x1aJ\n" +
	"\x1cDefaultContextModifiersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x03\n" +
	"\x17PromptGenerationRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12f\n" +
	"\x11dynamic_variables\x18\x02 \x03(\v29.prometheus.PromptGenerationRequest.DynamicVariablesEntryR\x10dynamicVariables\x12f\n" +
	"\x11context_modifiers\x18\x03 \x03(\v29.prometheus.PromptGenerationRequest.ContextModifiersEntryR\x10contextModifiers\x1aC\n" +
	"\x15DynamicVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15ContextModifiersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x01\n" +
	"\x0fGeneratedPrompt\x12#\n" +
	"\rprompt_string\x18\x01 \x01(\tR\fpromptString\x12E\n" +
	"\bmetadata\x18\x02 \x03(\v2).prometheus.GeneratedPrompt.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B4Z2github.com/your-username/prometheus-protocol/protob\x06proto3"

var (
	file_proto_prompt_messages_proto_rawDescOnce sync.Once
	file_proto_prompt_messages_proto_rawDescData []byte
)

func file_proto_prompt_messages_proto_rawDescGZIP() []byte {
	file_proto_prompt_messages_proto_rawDescOnce.Do(func() {
		file_proto_prompt_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_prompt_messages_proto_rawDesc), len(file_proto_prompt_messages_proto_rawDesc)))
	})
	return file_proto_prompt_messages_proto_rawDescData
}

var file_proto_prompt_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_prompt_messages_proto_goTypes = []any{
	(*PromptTemplate)(nil),          // 0: prometheus.PromptTemplate
	(*PromptGenerationRequest)(nil), // 1: prometheus.PromptGenerationRequest
	(*GeneratedPrompt)(nil),         // 2: prometheus.GeneratedPrompt
	nil,                             // 3: prometheus.PromptTemplate.DefaultContextModifiersEntry
	nil,                             // 4: prometheus.PromptGenerationRequest.DynamicVariablesEntry
	nil,                             // 5: prometheus.PromptGenerationRequest.ContextModifiersEntry
	nil,                             // 6: prometheus.GeneratedPrompt.MetadataEntry
}
var file_proto_prompt_messages_proto_depIdxs = []int32{
	3, // 0: prometheus.PromptTemplate.default_context_modifiers:type_name -> prometheus.PromptTemplate.DefaultContextModifiersEntry
	4, // 1: prometheus.PromptGenerationRequest.dynamic_variables:type_name -> prometheus.PromptGenerationRequest.DynamicVariablesEntry
	5, // 2: prometheus.PromptGenerationRequest.context_modifiers:type_name -> prometheus.PromptGenerationRequest.ContextModifiersEntry
	6, // 3: prometheus.GeneratedPrompt.metadata:type_name -> prometheus.GeneratedPrompt.MetadataEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_prompt_messages_proto_init() }
func file_proto_prompt_messages_proto_init() {
	if File_proto_prompt_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_prompt_messages_proto_rawDesc), len(file_proto_prompt_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_prompt_messages_proto_goTypes,
		DependencyIndexes: file_proto_prompt_messages_proto_depIdxs,
		MessageInfos:      file_proto_prompt_messages_proto_msgTypes,
	}.Build()
	File_proto_prompt_messages_proto = out.File
	file_proto_prompt_messages_proto_goTypes = nil
	file_proto_prompt_messages_proto_depIdxs = nil
}
