// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/prometheus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PromptObject represents a structured request to an AI model.
type PromptObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Temperature   float64                `protobuf:"fixed64,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,8,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptObject) Reset() {
	*x = PromptObject{}
	mi := &file_proto_prometheus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptObject) ProtoMessage() {}

func (x *PromptObject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prometheus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptObject.ProtoReflect.Descriptor instead.
func (*PromptObject) Descriptor() ([]byte, []int) {
	return file_proto_prometheus_proto_rawDescGZIP(), []int{0}
}

func (x *PromptObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PromptObject) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PromptObject) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PromptObject) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PromptObject) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *PromptObject) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PromptObject) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *PromptObject) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

// ConversationState represents the state of a conversation with an AI model.
type ConversationState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompts       []*PromptObject        `protobuf:"bytes,4,rep,name=prompts,proto3" json:"prompts,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationState) Reset() {
	*x = ConversationState{}
	mi := &file_proto_prometheus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationState) ProtoMessage() {}

func (x *ConversationState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prometheus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationState.ProtoReflect.Descriptor instead.
func (*ConversationState) Descriptor() ([]byte, []int) {
	return file_proto_prometheus_proto_rawDescGZIP(), []int{1}
}

func (x *ConversationState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConversationState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConversationState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConversationState) GetPrompts() []*PromptObject {
	if x != nil {
		return x.Prompts
	}
	return nil
}

func (x *ConversationState) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_prometheus_proto protoreflect.FileDescriptor

const file_proto_prometheus_proto_rawDesc = "" +
	"\n" +
	"\x16proto/prometheus.proto\x12\n" +
	"prometheus\"\xca\x02\n" +
	"\fPromptObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12E\n" +
	"\tvariables\x18\x05 \x03(\v2'.prometheus.PromptObject.VariablesEntryR\tvariables\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\a \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\b \x01(\x05R\tmaxTokens\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x02\n" +
	"\x11ConversationState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x122\n" +
	"\aprompts\x18\x04 \x03(\v2\x18.prometheus.PromptObjectR\aprompts\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.prometheus.ConversationState.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B4Z2github.com/your-username/prometheus-protocol/protob\x06proto3"

var (
	file_proto_prometheus_proto_rawDescOnce sync.Once
	file_proto_prometheus_proto_rawDescData []byte
)

func file_proto_prometheus_proto_rawDescGZIP() []byte {
	file_proto_prometheus_proto_rawDescOnce.Do(func() {
		file_proto_prometheus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_prometheus_proto_rawDesc), len(file_proto_prometheus_proto_rawDesc)))
	})
	return file_proto_prometheus_proto_rawDescData
}

var file_proto_prometheus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_prometheus_proto_goTypes = []any{
	(*PromptObject)(nil),      // 0: prometheus.PromptObject
	(*ConversationState)(nil), // 1: prometheus.ConversationState
	nil,                       // 2: prometheus.PromptObject.VariablesEntry
	nil,                       // 3: prometheus.ConversationState.MetadataEntry
}
var file_proto_prometheus_proto_depIdxs = []int32{
	2, // 0: prometheus.PromptObject.variables:type_name -> prometheus.PromptObject.VariablesEntry
	0, // 1: prometheus.ConversationState.prompts:type_name -> prometheus.PromptObject
	3, // 2: prometheus.ConversationState.metadata:type_name -> prometheus.ConversationState.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_prometheus_proto_init() }
func file_proto_prometheus_proto_init() {
	if File_proto_prometheus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_prometheus_proto_rawDesc), len(file_proto_prometheus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_prometheus_proto_goTypes,
		DependencyIndexes: file_proto_prometheus_proto_depIdxs,
		MessageInfos:      file_proto_prometheus_proto_msgTypes,
	}.Build()
	File_proto_prometheus_proto = out.File
	file_proto_prometheus_proto_goTypes = nil
	file_proto_prometheus_proto_depIdxs = nil
}
